// <auto-generated />
using MedalsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedalsApi.Migrations
{
    [DbContext(typeof(MedalsDbContext))]
    partial class MedalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("MedalsApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bronze")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Silver")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bronze = 3,
                            Gold = 2,
                            Name = "United States",
                            Silver = 2
                        },
                        new
                        {
                            Id = 2,
                            Bronze = 0,
                            Gold = 3,
                            Name = "China",
                            Silver = 1
                        },
                        new
                        {
                            Id = 3,
                            Bronze = 2,
                            Gold = 0,
                            Name = "France",
                            Silver = 2
                        },
                        new
                        {
                            Id = 4,
                            Bronze = 2,
                            Gold = 0,
                            Name = "Germany",
                            Silver = 2
                        },
                        new
                        {
                            Id = 5,
                            Bronze = 0,
                            Gold = 1,
                            Name = "Spain",
                            Silver = 1
                        },
                        new
                        {
                            Id = 6,
                            Bronze = 3,
                            Gold = 0,
                            Name = "United Kingdom",
                            Silver = 2
                        },
                        new
                        {
                            Id = 7,
                            Bronze = 0,
                            Gold = 3,
                            Name = "Brazil",
                            Silver = 0
                        },
                        new
                        {
                            Id = 8,
                            Bronze = 2,
                            Gold = 2,
                            Name = "Italy",
                            Silver = 2
                        },
                        new
                        {
                            Id = 9,
                            Bronze = 2,
                            Gold = 1,
                            Name = "Switzerland",
                            Silver = 1
                        },
                        new
                        {
                            Id = 10,
                            Bronze = 1,
                            Gold = 0,
                            Name = "Poland",
                            Silver = 2
                        },
                        new
                        {
                            Id = 11,
                            Bronze = 1,
                            Gold = 0,
                            Name = "Sweden",
                            Silver = 3
                        },
                        new
                        {
                            Id = 12,
                            Bronze = 0,
                            Gold = 2,
                            Name = "Ireland",
                            Silver = 1
                        },
                        new
                        {
                            Id = 13,
                            Bronze = 2,
                            Gold = 3,
                            Name = "Scotland",
                            Silver = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
